package com.sw.viewMejorada;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author Nicolás
 */
public class VistaSeleccion extends javax.swing.JFrame
{

    /**
     * Creates new form VistaSeleccion
     */
    public VistaSeleccion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        filler4 = new Box.Filler(new Dimension(10, 0), new Dimension(10, 0), new Dimension(10, 32767));
        jPanel2 = new JPanel();
        filler2 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jLabel2 = new JLabel();
        filler1 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        filler3 = new Box.Filler(new Dimension(15, 0), new Dimension(15, 0), new Dimension(15, 32767));
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        filler5 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new Dimension(320, 160));
        setMinimumSize(new Dimension(320, 160));
        setPreferredSize(new Dimension(320, 160));
        getContentPane().add(filler4, BorderLayout.WEST);

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        jPanel2.add(filler2);

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Algoritmo a simular");
        jLabel2.setAlignmentX(0.5F);
        jPanel2.add(jLabel2);
        jPanel2.add(filler1);

        getContentPane().add(jPanel2, BorderLayout.NORTH);
        getContentPane().add(filler3, BorderLayout.EAST);

        jPanel1.setLayout(new GridLayout(2, 1, 0, 5));

        jButton1.setText("Short Remainig Time First");
        jPanel1.add(jButton1);

        jButton2.setText("Round Robin");
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, BorderLayout.CENTER);
        getContentPane().add(filler5, BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>


        /* Create and display the form */
        EventQueue.invokeLater(() ->
        {
            VistaSeleccion vista = new VistaSeleccion();
            vista.setVisible(true);
            vista.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Box.Filler filler1;
    private Box.Filler filler2;
    private Box.Filler filler3;
    private Box.Filler filler4;
    private Box.Filler filler5;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
