package com.sw.viewMejorada;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolás
 */
public class VistaGrafica extends javax.swing.JFrame
{

    public VistaGrafica()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel7 = new JPanel();
        jLabel1 = new JLabel();
        filler1 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        filler2 = new Box.Filler(new Dimension(0, 10), new Dimension(0, 10), new Dimension(32767, 10));
        jPanel8 = new JPanel();
        jButton3 = new JButton();
        jPanel9 = new JPanel();
        jButton4 = new JButton();
        jSplitPane1 = new JSplitPane();
        jPanel6 = new JPanel();
        jScrollPane3 = new JScrollPane();
        jTable3 = new JTable();
        jPanel4 = new JPanel();
        jPanel5 = new JPanel();
        jPanel2 = new JPanel();
        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel3 = new JPanel();
        jScrollPane2 = new JScrollPane();
        jTable2 = new JTable();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(800, 400));
        setPreferredSize(new Dimension(1000, 600));

        jPanel7.setLayout(new BorderLayout());

        jLabel1.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Simulación");
        jPanel7.add(jLabel1, BorderLayout.CENTER);
        jPanel7.add(filler1, BorderLayout.PAGE_END);
        jPanel7.add(filler2, BorderLayout.PAGE_START);

        jPanel8.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 5));

        jButton3.setText("Iniciar simulación");
        jPanel8.add(jButton3);

        jPanel7.add(jPanel8, BorderLayout.LINE_END);

        jPanel9.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 5));

        jButton4.setText("Regresar");
        jPanel9.add(jButton4);

        jPanel7.add(jPanel9, BorderLayout.LINE_START);

        getContentPane().add(jPanel7, BorderLayout.NORTH);

        jPanel6.setBorder(BorderFactory.createTitledBorder("Tiempos de espera"));
        jPanel6.setLayout(new BorderLayout());

        jScrollPane3.setMinimumSize(new Dimension(200, 23));

        jTable3.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Proceso", "Tiempo espera"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel6.add(jScrollPane3, BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel6);

        jPanel4.setBorder(BorderFactory.createTitledBorder(null, "Representación gráfica", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.TOP));
        jPanel4.setMinimumSize(new Dimension(400, 123));
        jPanel4.setPreferredSize(new Dimension(400, 498));
        jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));

        jPanel5.setBackground(new Color(255, 204, 204));

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        jSplitPane1.setRightComponent(jPanel4);

        getContentPane().add(jSplitPane1, BorderLayout.CENTER);

        jPanel2.setMinimumSize(new Dimension(270, 92));
        jPanel2.setPreferredSize(new Dimension(270, 850));
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        jPanel1.setBorder(BorderFactory.createTitledBorder("Datos recuperados"));
        jPanel1.setLayout(new BorderLayout());

        jTable1.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "ID", "Proceso", "Tiempo ráf.", "Tiempo lleg."
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jPanel1.add(jScrollPane1, BorderLayout.CENTER);

        jPanel2.add(jPanel1);

        jPanel3.setBorder(BorderFactory.createTitledBorder("Procesos finalizados"));
        jPanel3.setLayout(new BorderLayout());

        jTable2.setModel(new DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "ID", "Proceso", "Tiempo ráf.", "Tiempo lleg."
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0)
        {
            jTable2.getColumnModel().getColumn(0).setMinWidth(30);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jPanel3.add(jScrollPane2, BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() ->
        {
            VistaGrafica vista = new VistaGrafica();
            vista.setVisible(true);
            vista.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Box.Filler filler1;
    private Box.Filler filler2;
    private JButton jButton3;
    private JButton jButton4;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JSplitPane jSplitPane1;
    private JTable jTable1;
    private JTable jTable2;
    private JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
